### ISSUE TITLE
[0.16.0] Scoped component :host isn't applied properly

### ISSUE THREAD

**Issue by Nightbr** [ionic-team/stencil#1260]
**Stencil version:**
```
 @stencil/core@0.16.0
```

**I'm submitting a:**
[X ] bug report

**Current behavior:**
When we have a scoped component, the style isn't properly applied. 

**Expected behavior:**
The style should be applied properly to scoped component.

**Steps to reproduce:**
1- Create a scoped component:
2- Build or run dev 
3- Open an html page with the component
4- Look at the style, it is not applied correctly

**Related code:**
my-component.tsx
```tsx
import { Component, Prop } from '@stencil/core';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.scss',
  scoped: true
})
export class MyComponent {
  /**
   * Boolean to indicate if this navlink is active
   */
  @Prop()
  active?: boolean;

  hostData() {
    return {
      class: {
        ...(this.active === true
          ? {
              [`is-active`]: true
            }
          : '')
      }
    };
  }

  render() {
    return [
      <a href={this.href}>
        <slot />
      </a>
    ];
  }
}
```
my-component.scss

```scss
:host {
  $color: #787993;

  margin-left: 24px;
  cursor: pointer;

  a {
    font-family: $font-family-base;
    color: $color;
    font-size: 14px;
    font-weight: 500;
    text-decoration: none;

    &:visited {
      text-decoration: none;
      color: $color;
    }

    &:hover {
      text-decoration: none;
      color: blue;
    }
  }
}

:host(.is-active) {
  a {
    color: $primary;
  }
}
```

**Other information:**
With further debug, it seems to be an issue with stencil not set the correct class sc-my-component is never set. Instead: `sc-my-component-default-h sc-my-component-default-s  hydrated` is set. It should be : `sc-my-component-h sc-my-component-s  hydrated` in order to work with the generated CSS.

Feel free to ask my further debug.

Regards
