### ISSUE TITLE
Nested components always rendered as the first child

### ISSUE THREAD

**Issue by marvinhagemeister** [ionic-team/stencil#141]
Just upgraded to the latest pre-release of `core@0.0.5-17` and noticed that nested components render a bit strange.

```tsx
<x-foo>
  <x-bar />
</x-foo>
```

The render method of `x-foo` is:

```tsx
render() {
  return (
    <div class="foo">
      <slot />
    </div>
   );
}
```
But the resulting html is:

```html
<x-foo>
  <x-bar />
  <div class="foo"></div>
</x-foo>
```

I can reproduce this behaviour with any component. The nested child seems to always be rendered as the first child.

**Comment by mlynch** [comment]
Which browser(s)?

**Comment by marvinhagemeister** [comment]
Can reproduce this in all modern browsers (safari, chrome, Firefox)

**Comment by adamdbradley** [comment]
Ok thanks, we'll take a look

**Comment by obedm503** [comment]
I'm also, having the same issue with `0.0.5-17`

**Comment by motss** [comment]
Was happily to see `<slot />` being documented quite recently but was hit by this unexpected behavior.

Had no choice but to refactor all our codes to accept just one `slot` element:

```tsx
/** my-element.tsx */
...
render() {
  return (
    <slot />
  );
}
...
```

```tsx
/** index.html */
...
<my-element>
  <div class="content-container">
    <div>My App></p>
    <div class="flex"></div>
    <button class="icon-button">sign in</button>
  </div>
</my-element>
...
```

```scss
/** my-element.scss */
my-element {
  * {
    box-sizing: border-box;
  }

  .content-container {
    display: flex;
    flex-direction: row;
    align-items: center;
    padding: 0 16px;
  }

  /** :host equivalent */
  display: block;
  box-sizing: border-box;
}
```

Instead of something like this where `.content-container` can have a flex layout and the slotted elements are the children.

```tsx
/** my-element.tsx */
...
render() {
  return (
   <div class="content-container">
     <slot />
   </div>
  );
}
...
```

```tsx
/** index.html */
...
<my-element>
  <div>My App></p>
  <div class="flex"></div>
  <button class="icon-button">sign in</button>
</my-element>
...
```
