### ISSUE TITLE
CSS Custom Properties vs IE11 when moving an element

### ISSUE THREAD

**Issue by cary-smith** [ionic-team/stencil#1615]
**Stencil version:**

```
 @stencil/core@1.0.0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
If a component has a custom property in its CSS and is moved from one spot to another via element.appendChild(), then the style tag is permanently removed from the header. 

**Expected behavior:**

If the element is not being 'removed' from the screen then the style tag should remain regardless of custom properties or not.

**Steps to reproduce:**

1. run `git clone -b IE11-css-loss git@github.com:cary-smith/stencil-component-starter.git`
1. run `npm i`
1. run `npm start`
1. Open IE11 to `http://localhost:3333`
1. Click the button
1. Notice the lack of styling still being applied

**Related code:**

```css
:host {
  background-color: lightblue;
  border: 1px solid var(--maybe-black, black); /** This is the problem child */
  display: block;
  padding: 2em;
  margin: 2em;
  font-weight: bolder;
}
```

**Other information:**

Not sure, but this may be related to https://github.com/ionic-team/stencil/issues/1596 since they both run into pain with custom props.

Thanks for the incredible software! If it weren't for the 'evil one' holding back the interwebs this would be smooth sailing.
