### ISSUE TITLE
Animation/Transition event names not converted correctly

### ISSUE THREAD

**Issue by rayniervandam** [ionic-team/stencil#1906]
**Stencil version:**

```
 @stencil/core@1.5.3
```

**I'm submitting a:**

[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When using animation or transition events on elements (ex: **onAnimationEnd**), they get interpreted as custom events, resulting in them ending up with the wrong name (**animationEnd** instead of **animationend**) causing them not to trigger correctly. 

***Note***: The event name succeeds the **[isMemberInElement](https://github.com/ionic-team/stencil/blob/ccce46e55e796e843530bbd9d40a2b40b2118f80/src/runtime/vdom/set-accessor.ts#L72)** check in Firefox 69 and Edge, making it so it's recognized as a standard event, causing this bug to so far only occur in Chrome 77

**Expected behavior:**

Animation and transition events like **onAnimationEnd** should be interpreted as standard events instead of custom events and converted to full lowercase (**animationend**)

**Steps to reproduce:**

1. Use the component as defined below
2. Open the console
3. No console message is displayed after animation finishes

**Related code:**

stencil-animation-event.tsx
```tsx
import { Component, h } from '@stencil/core';

@Component({
  tag: 'stencil-animation-event',
  styleUrl: 'stencil-animation-event.css',
  shadow: true
})
export class AnimationEvents {
  render() {
    return (
      <div class="animation" onAnimationEnd={() => console.log('Animation Ended.')}>
        Example text
      </div>
    );
  }
}
```

stencil-animation-event.css
```css
.animation {
    animation: rotate 1s linear;
    transform-origin: center center;
    text-align: center;
}
@keyframes rotate {
    from {
        transform: rotate(0deg);
    }
    to {
        transform: rotate(360deg);
    }
}
```

**Other information:**

Preact had this exact same issue, see: 
https://github.com/preactjs/preact/issues/1589

They fixed it with the following PR(s):
https://github.com/preactjs/preact/pull/1590
https://github.com/preactjs/preact/pull/1631
https://github.com/preactjs/preact/pull/1804
