### ISSUE TITLE
Scoped styles not scoping the tag selector properly

### ISSUE THREAD

**Issue by DesignByOnyx** [ionic-team/stencil#1912]
**Stencil version:**
```
 @stencil/core@1.5.4
```

**I'm submitting a:**
[x] bug report
[ ] feature request
[ ] support request

**Current behavior:**
This is identical to https://github.com/ionic-team/stencil/issues/1215 - but this is still a bug as the compiled output is not what is expected.
When creating a component with `scoped: true`, and using the custom tag in the CSS file, the tag is improperly scoped.

```ts
@Component({
  tag: 'rjs-hello',
  styleUrl: 'hello.css',
  scoped: true
})
export class RjsHello { ... }
```

Styles:
```css
rjs-hello {
  background-color: red;
}
```

Renders as:
```html
<!-- note the CSS selector is missing the `-h` suffix -->
<style>rjs-hello.sc-rjs-hello{ background-color: red }</style>
<rjs-hello class="sc-rjs-hello-h sc-rjs-hello-s hydrated">
    World
</rjs-hello>
```

**Expected behavior:**
The compiled CSS does not target the custom element because the class names do not match. I would expect one of the following scoped styles:
- `rjs-hello.sc-rjs-hello-h { ... }` - notice the `-h` suffix
- `.sc-rjs-hello-h rjs-hello { ... }` - these styles would not be applied, but at least the output is what you would expect and you could fix the problem without scratching your head.

**Note:** Changing the CSS to use `:host { }` instead of `rjs-hello { }` works, but that does not address the underlying problem with the unexpected output.

**Steps to reproduce:**
```
git clone https://github.com/DesignByOnyx/stencil-scoped-bug.git
cd stencil-scoped-bug
npm install
npm run start
```
Observe: the component should have a red background.

**Related code:**

https://github.com/DesignByOnyx/stencil-scoped-bug

**Comment by manucorporat** [comment]
Styles that apply to the host element need to use `:host`:
```
:host {
  background-color: red;
}
```

scoped is just like shadow, but simulated instead of native shadow-dom encapsulation

https://stenciljs.com/docs/styling#things-to-remember-with-shadow-dom

**Comment by manucorporat** [comment]
>Changing the CSS to use :host { } instead of rjs-hello { } works, but that does not address the underlying problem with the unexpected output.

I might be  missing something, but your expectation are not correct.
```
rjs-hello {
  background-color: red;
}
```
would target a `rjs-hello` element inside your component, not the host element:
```
render() {
  return <rjs-hello/>;
}
```

**Comment by DesignByOnyx** [comment]
Correct! It's hard to describe this, so please stick with me. When I write this:

```css
rjs-hello {
  background-color: red;
}
p {
  color: blue;
}
```
It gets compiled to this:
```css
rjs-hello.sc-rjs-hello {        /* See how a class is APPENDED to my custom tag selector */
  background-color: red;
}
.sc-rjs-hello-h p {             /* See how a class is added BEFORE the P selector */
  color: blue;
}
```
With the above output, it made me think **_"ok, stencil is trying to scope my custom tag, but they are forgetting to add the `-h` suffix... this must be a bug"_**... which is confusing, which brought me here. The same thing also happened for #1215. 

If you generated the following code, the confusion goes away:
```css
.sc-rjs-hello-h rjs-hello {
  background-color: red;
}
.sc-rjs-hello-h p {
  color: blue;
}
```
At least I can see the scoping happening and fix the issue without thinking that there's a bug. Does that make sense?

**Comment by DesignByOnyx** [comment]
Furthermore, it doesn't quite make sense to use `:host` when not using a shadow dom. It felt natural for me to use my custom tag name as I did above. In such a case, I would expect stencil to generate the same output as today, but with a valid class name (eg. with the `-h` suffix). So if I write this:

```css
rjs-hello {
  background-color: red;
}
p {
  color: blue;
}
```
It would be nice to have it compile to this:
```css
rjs-hello.sc-rjs-hello-h {   /* notice the -h suffix */
  background-color: red;
}
.sc-rjs-hello-h p {          /* notice the -h suffix */
  color: blue;
}
```

**Comment by manucorporat** [comment]
So, i am reopening, but this css with `scoped: true`:
```css
rjs-hello {
  background-color: red;
}
p {
  color: blue;
}
```

is generating this:
```css
rjs-hello.sc-my-component {
  background-color: red;
}
p.sc-my-component {
  color: blue;
}
```

**Comment by manucorporat** [comment]
"scoped" is shadow-dom without native shadow-dom, in fact scoped is the same code that polyfills shadow-dom in browsers that does not support shadow-dom.

We don't want to invent another scoping css syntax when shadow-dom covers the use case in addition, web component can be defined with different tag names:


``
`
customElements.define('my-toggle, IonToggle);
customElements.define('your-toggle, IonToggle);
```

Writting `:host` makes your css independent of the tag name, which is really useful for real encapsulation.

>Furthermore, it doesn't quite make sense to use :host when not using a shadow dom. It felt natural for me to use my custom tag name as I did above. In such a case, I would expect stencil to generate the same output as today, but with a valid class name (eg. with the -h suffix). So if I write this:

```
rjs-hello {
  background-color: red;
}
p {
  color: blue;
}
```

how would you target a `<rjs-hello>` inside a `<rjs-hello>` then?

**Comment by manucorporat** [comment]
If you want to use `rjs-hello`, i would not use any encapsulation, no scoped, no shadow. That way it would work as you describe!

**Comment by DesignByOnyx** [comment]
My big hangup is this (sorry for the repetition). Today, stencil compiles to this:

```css
rjs-hello.sc-rjs-hello { /* The class is APPENDED to my custom tag selector, AND the class is invalid */
  background-color: red;
}
.sc-rjs-hello-h p {  /* See how a class is added BEFORE the selector */
  color: blue;
}
```
Stencil is not adding the class BEFORE my custom tag, it's APPENDING the class (an invalid one at that). I would expect one of the following:

1) Add the class BEFORE the custom tag like you do with every other selector
2) APPEND the correct class with "-h" suffix

It doesn't matter which one you choose to implement as long as you don't continue doing it the way you are today... which is very confusing.
