### ISSUE TITLE
Cannot style component hosts using :root and adjacent sibling (+) selectors

### ISSUE THREAD

**Issue by gtranter** [ionic-team/stencil#1943]
**Stencil version:**
```
 @stencil/core@1.4.0
```

**I'm submitting a:**
[ x] bug report

**Current behavior:**
Style defined using :root selector does not work when defined in a component with shadow: true. If shadow: false is used, :root works fine.

**Expected behavior:**
Style defined using :root should work when loaded by the component.

**Steps to reproduce:**
I've included a sample component below. The idea is that when clicked (made active), the component should change color and label. When clicked again, the color and label change back (this is a toggle). But when the component is immediately after another one of the components which is active, the color does not change, only the label. The style toggle is implemented by adding a class to the host via component state changes. The class is properly applied.

**Related code:**

TSX
```tsx
import { Component, Host, h, State } from '@stencil/core';

@Component({
    tag: 'test-after-style',
    styleUrl: 'test-after-style.scss',
    shadow: true
})
export class TestAfterStyle {
    @State() isActive: boolean = false;

    toggle() {
        this.isActive = !this.isActive;
    }

    render() {
        return (
            <Host
                onClick={() => this.toggle()}
                class={{
                    'test-after-style-active': this.isActive,
                }}
            >
                { this.isActive ? 'Active' : 'Dormant' }
            </Host>
        );
    }
}
```
SCSS
```scss
:host {
    cursor: pointer;
    display: flex;
    justify-content: space-between;
    padding: .8em;
    transition: background-color 150ms linear;
    background-color: #e8e8e8;
    margin-top: 2px;

    &:hover {
        background-color: #00e800;
    }
}

:host(.test-after-style-active) {
    background-color: #00e800;
}

:root {
    .test-after-style-active + .test-after-style-active {
        background-color: #e8e8e8;
    }
}
```
**Other information:**
Note that I am attempting to style the component host element itself, not its shadow dom.
I've tried using the adjacent sibling selector in different ways to get this functionality but nothing works. Examples:
```
:host(.test-after-style-active) + :host(.test-after-style-active) {
    background-color: #e8e8e8;
}
```
```
:host(.test-after-style-active + .test-after-style-active) {
    background-color: #e8e8e8;
}
```
