### ISSUE TITLE
CSS Variables don't work with `shadow: true`

### ISSUE THREAD

**Issue by chris-dura** [ionic-team/stencil#2193]
**Stencil version:**

```
 @stencil/core@1.8.7
 @stencil/sass@1.1.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

CSS Custom Properties are not being applied to components when `shadow: true`

**Expected behavior:**

Defining CSS custom properties on the `:root` should penetrate Shadow DOM.

https://codepen.io/chris-dura/pen/eYNpNqd

**Steps to reproduce:**

1. Initialize project with `npm init stencil`
2. Install `@stencil/sass`
3. Add `global.scss` with a CSS variable defined on `:root`
4. Add `global.scss` to `injectGlobalPaths`
5. Run `npm start`

**Related code:**
```ts
// stencil.config.ts

  plugins: [
    postcss({
      plugins: [autoprefixer()],
    }),
    sass({
      injectGlobalPaths: [
        'src/global/global.scss'
      ]
    })
  ]
```
```scss
// global.scss

:root {
  --my-primary-color: green;
}
```
```tsx
// my-component.tsx

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.scss',
  shadow: true
})
...
```
```scss
// my-component.scss

div {
  background-color: var(--my-primary-color, red);
}
```

**Other information:**
