### ISSUE TITLE
Nested CSS classes behave inconsistently across browsers

### ISSUE THREAD

**Issue by zurfluh** [ionic-team/stencil#2555]
**Stencil version:**

```
 @stencil/core@1.15.0
```

**I'm submitting a:**

[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Nested CSS classes are not scoped in IE and MS-Edge, leading to different behaviour compared to browsers with shadow DOM.

**Expected behavior:**
Same styling in IE and MS-Edge.

**Steps to reproduce:**
1. Use nested CSS classes (see snippet below).
2. Use the component by a web page which styles the inner element (here: `.header`).
3. Compare browsers with and without shadow DOM.
  i. with: web page style is not applied to component
  ii. without: web page style is applied to component

**Related code:**
```scss
.navibar {
  > li.header {
        border-top: 1px solid #777;
        color: #777;
        font-size: 11px;
        padding-left: 10px;
      }
}
```
```tsx
@Component({
  tag: 'foo',
  styleUrl: 'foo.scss',
  shadow: true
})
...
```

**Other information:**
I am opening this issue in this project because I do not know whether it is related to stencil-sass or not.
