### ISSUE TITLE
CSS Variables are not documented using docs-readme output target

### ISSUE THREAD

**Issue by danschultz** [ionic-team/stencil#3034]
**Stencil version:**

```
 @stencil/core@2.7.1
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

I'm using the `docs-readme` output target. Starting with Stencil v2.7.0, CSS variables are no longer being documented in the generated `readme.md` files.

**Expected behavior:**

CSS variables that have documentation should be documented in the generated `readme.md` files.

**Steps to reproduce:**

Document a CSS variable like this:

```css
:host {
  /**
   * @prop --my-background: Some documentation.
   */
  --my-background: red;
}
```

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**
