### ISSUE TITLE
Stencil unescapes unicode characters in the content attribute incorrectly

### ISSUE THREAD

**Issue by richardruiter** [ionic-team/stencil#545]
**Stencil version:**

```
 @stencil/core@0.6.0-0
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

there is a bug in stencil that as unescapes unicode characters in the content attribute incorrectly

**Expected behavior:**

**Steps to reproduce:**

```css
.myclass:before {
   content: "\F113";
}
```

In the component is compiled to
```js
static get style() { return ".myclass:before {content: \"\F113\";}" }
```

When inspected in the browser you see that the slash is removed
```css
.myclass:before {content: "F113";}
```
