### ISSUE TITLE
feat: hydrate - Remove scoped css classes if serializeShadowRoot is true.

### ISSUE THREAD

**Issue by mayerraphael** [ionic-team/stencil#5880]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently Stencil scopes the CSS inside the Declarative Shadow DOM, which is not necessary anymore, as they are already isolated.

The bigger problem is that this bloats the size of the HTML massively. 

### Describe the Use Case

A simple css class like 

```css
.left-0 {left:var(--spacing-0)}
```

is bloated to

```css
/*!@.left-0*/.left-0.sc-my-maybe-long-component-name{left:var(--spacing-0)}
```

This round about triples the size of css classes.

Here another example:

```css
/*!@.button.primary:focus-within.focus-wcag-none:not(:hover,:active,.suppressFocusStyle)*/
.button.primary.sc-my-maybe-long-component-name:focus-within.focus-wcag-none:not(:hover, .sc-my-maybe-long-component-name:active, .suppressFocusStyle).sc-my-maybe-long-component-name {
    outline: 2px solid var(--button-stroke-primary-focus)
}
```

### Describe Preferred Solution

No additional classname CSS selector necessary. No CSS comments necessary.
